export const DONNEES_CONFIGURATION_SYSTEME = [
  {
    cle: 'application.nom',
    valeurTexte: 'Backend KYA',
    typeValeur: 'STRING',
    portee: 'GLOBAL',
    scopeCle: 'GLOBAL',
    origine: 'DEFAULT',
    verrouille: false,
  },
  {
    cle: 'application.mode',
    valeurTexte: 'development',
    typeValeur: 'STRING',
    portee: 'GLOBAL',
    scopeCle: 'GLOBAL',
    origine: 'DEFAULT',
    verrouille: false,
  },
  {
    cle: 'maintenance.active',
    valeurBooleen: false,
    typeValeur: 'BOOLEAN',
    portee: 'GLOBAL',
    scopeCle: 'GLOBAL',
    origine: 'DEFAULT',
    verrouille: false,
  },
  {
    cle: 'paiement.joursGrace',
    valeurNombre: 5,
    typeValeur: 'NUMBER',
    portee: 'GLOBAL',
    scopeCle: 'GLOBAL',
    origine: 'DEFAULT',
    verrouille: false,
  },
  {
    cle: 'abonnement.modeDefaut',
    valeurTexte: 'monthly',
    typeValeur: 'STRING',
    portee: 'GLOBAL',
    scopeCle: 'GLOBAL',
    origine: 'DEFAULT',
    verrouille: false,
  },
  {
    cle: 'notification.email.active',
    valeurBooleen: true,
    typeValeur: 'BOOLEAN',
    portee: 'GLOBAL',
    scopeCle: 'GLOBAL',
    origine: 'DEFAULT',
    verrouille: false,
  },
  {
    cle: 'notification.sms.active',
    valeurBooleen: false,
    typeValeur: 'BOOLEAN',
    portee: 'GLOBAL',
    scopeCle: 'GLOBAL',
    origine: 'DEFAULT',
    verrouille: false,
  },
  {
    cle: 'notification.whatsapp.active',
    valeurBooleen: false,
    typeValeur: 'BOOLEAN',
    portee: 'GLOBAL',
    scopeCle: 'GLOBAL',
    origine: 'DEFAULT',
    verrouille: false,
  },
]
