export const VALEURS_TYPE_TENTATIVE_CONNEXION_AUTHENTIFICATION = {
  LOGIN: 'LOGIN',
  SECOND_AUTH: 'SECOND_AUTH',
  REFRESH: 'REFRESH',
} as const

export type TypeTentativeConnexionAuthentification =
  (typeof VALEURS_TYPE_TENTATIVE_CONNEXION_AUTHENTIFICATION)[keyof typeof VALEURS_TYPE_TENTATIVE_CONNEXION_AUTHENTIFICATION]
