import type { TypeDependancesServiceAdministrationAdminLocations } from '@/src/application/types/administration/clients/TypeDependancesServiceAdministrationAdminLocations'

export type TypeDependancesServiceAdministrationAdminClientsLocations =
  TypeDependancesServiceAdministrationAdminLocations
