export type TypeRessourceAdministrationAdmin =
  | 'clients'
  | 'documents'
  | 'payments'
  | 'deposits'
  | 'work_items'
  | 'settings'
  | 'import_runs'
  | 'notifications'
  | 'undo-actions'
  | 'admin_payments'
  | 'audit_logs'
  | 'blocked_ips'
  | 'cloudinary'
