var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/documentation/route.js")
R.c("server/chunks/node_modules_next_f8e1121d._.js")
R.c("server/chunks/node_modules_validator_bf3191fe._.js")
R.c("server/chunks/node_modules_js-yaml_cd408f23._.js")
R.c("server/chunks/node_modules_yaml_4a00c01a._.js")
R.c("server/chunks/node_modules_d8a9075e._.js")
R.c("server/chunks/[root-of-the-server]__b52dc8eb._.js")
R.c("server/chunks/_next-internal_server_app_api_documentation_route_actions_e8db8419.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/documentation/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/documentation/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
