// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/docs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/docs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/documentation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documentation">> = Specific
  const handler = {} as typeof import("../../../app/documentation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/swagger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/swagger">> = Specific
  const handler = {} as typeof import("../../../app/swagger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin_payments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin_payments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin_payments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin_payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin_payments">> = Specific
  const handler = {} as typeof import("../../../app/admin_payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin_payments/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin_payments/status">> = Specific
  const handler = {} as typeof import("../../../app/admin_payments/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin_payments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin_payments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin_payments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin_payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin_payments">> = Specific
  const handler = {} as typeof import("../../../app/api/admin_payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin_payments/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin_payments/status">> = Specific
  const handler = {} as typeof import("../../../app/api/admin_payments/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin_requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin_requests/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin_requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin_requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin_requests">> = Specific
  const handler = {} as typeof import("../../../app/api/admin_requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admins/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admins/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admins/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admins">> = Specific
  const handler = {} as typeof import("../../../app/api/admins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit_logs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit_logs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/audit_logs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit_logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit_logs">> = Specific
  const handler = {} as typeof import("../../../app/api/audit_logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/pending-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/pending-check">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/pending-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/clear-impersonation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/clear-impersonation">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/clear-impersonation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/impersonate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/impersonate">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/impersonate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/login">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/rafraichir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/rafraichir">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/rafraichir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/super-admin/second-auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/super-admin/second-auth">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/super-admin/second-auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/super-admin/totp/activer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/super-admin/totp/activer">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/super-admin/totp/activer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/super-admin/totp/initialiser/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/super-admin/totp/initialiser">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/super-admin/totp/initialiser/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/authContext/super-admin/totp/statut/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/authContext/super-admin/totp/statut">> = Specific
  const handler = {} as typeof import("../../../app/api/authContext/super-admin/totp/statut/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/blocked_ips/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blocked_ips/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/blocked_ips/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/blocked_ips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blocked_ips">> = Specific
  const handler = {} as typeof import("../../../app/api/blocked_ips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients">> = Specific
  const handler = {} as typeof import("../../../app/api/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cloudinary/open-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cloudinary/open-url">> = Specific
  const handler = {} as typeof import("../../../app/api/cloudinary/open-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/deposits/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deposits/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/deposits/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/deposits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deposits">> = Specific
  const handler = {} as typeof import("../../../app/api/deposits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/documentation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documentation">> = Specific
  const handler = {} as typeof import("../../../app/api/documentation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents">> = Specific
  const handler = {} as typeof import("../../../app/api/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/entreprises/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entreprises/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/entreprises/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/entreprises/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entreprises">> = Specific
  const handler = {} as typeof import("../../../app/api/entreprises/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import_runs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import_runs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/import_runs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import_runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import_runs">> = Specific
  const handler = {} as typeof import("../../../app/api/import_runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/locations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/locations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations">> = Specific
  const handler = {} as typeof import("../../../app/api/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sante/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sante">> = Specific
  const handler = {} as typeof import("../../../app/api/sante/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/securite/audits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/securite/audits">> = Specific
  const handler = {} as typeof import("../../../app/api/securite/audits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sign">> = Specific
  const handler = {} as typeof import("../../../app/api/sign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/undo-actions/[id]/rollback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/undo-actions/[id]/rollback">> = Specific
  const handler = {} as typeof import("../../../app/api/undo-actions/[id]/rollback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/undo-actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/undo-actions">> = Specific
  const handler = {} as typeof import("../../../app/api/undo-actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/work_items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/work_items/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/work_items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/work_items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/work_items">> = Specific
  const handler = {} as typeof import("../../../app/api/work_items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/audit_logs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/audit_logs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/audit_logs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/audit_logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/audit_logs">> = Specific
  const handler = {} as typeof import("../../../app/audit_logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/session">> = Specific
  const handler = {} as typeof import("../../../app/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/clear-impersonation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/clear-impersonation">> = Specific
  const handler = {} as typeof import("../../../app/authContext/clear-impersonation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/impersonate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/impersonate">> = Specific
  const handler = {} as typeof import("../../../app/authContext/impersonate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/login">> = Specific
  const handler = {} as typeof import("../../../app/authContext/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/logout">> = Specific
  const handler = {} as typeof import("../../../app/authContext/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/rafraichir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/rafraichir">> = Specific
  const handler = {} as typeof import("../../../app/authContext/rafraichir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext">> = Specific
  const handler = {} as typeof import("../../../app/authContext/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/super-admin/second-auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/super-admin/second-auth">> = Specific
  const handler = {} as typeof import("../../../app/authContext/super-admin/second-auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/super-admin/totp/activer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/super-admin/totp/activer">> = Specific
  const handler = {} as typeof import("../../../app/authContext/super-admin/totp/activer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/super-admin/totp/initialiser/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/super-admin/totp/initialiser">> = Specific
  const handler = {} as typeof import("../../../app/authContext/super-admin/totp/initialiser/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/authContext/super-admin/totp/statut/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/authContext/super-admin/totp/statut">> = Specific
  const handler = {} as typeof import("../../../app/authContext/super-admin/totp/statut/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blocked_ips/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/blocked_ips/[id]">> = Specific
  const handler = {} as typeof import("../../../app/blocked_ips/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blocked_ips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/blocked_ips">> = Specific
  const handler = {} as typeof import("../../../app/blocked_ips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../app/clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/clients">> = Specific
  const handler = {} as typeof import("../../../app/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cloudinary/open-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/cloudinary/open-url">> = Specific
  const handler = {} as typeof import("../../../app/cloudinary/open-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/deposits/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/deposits/[id]">> = Specific
  const handler = {} as typeof import("../../../app/deposits/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/deposits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/deposits">> = Specific
  const handler = {} as typeof import("../../../app/deposits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/documents/[id]">> = Specific
  const handler = {} as typeof import("../../../app/documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/documents">> = Specific
  const handler = {} as typeof import("../../../app/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/import_runs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/import_runs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/import_runs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/import_runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/import_runs">> = Specific
  const handler = {} as typeof import("../../../app/import_runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/notifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../../app/notifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../app/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/payments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/payments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../../app/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/settings/[id]">> = Specific
  const handler = {} as typeof import("../../../app/settings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sign">> = Specific
  const handler = {} as typeof import("../../../app/sign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/undo-actions/[id]/rollback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/undo-actions/[id]/rollback">> = Specific
  const handler = {} as typeof import("../../../app/undo-actions/[id]/rollback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/undo-actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/undo-actions">> = Specific
  const handler = {} as typeof import("../../../app/undo-actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/work_items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/work_items/[id]">> = Specific
  const handler = {} as typeof import("../../../app/work_items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/work_items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/work_items">> = Specific
  const handler = {} as typeof import("../../../app/work_items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
